<?php

namespace frontend\controllers;

use Yii;
use frontend\models\ContactForm;
use yii\web\Controller;
use common\models\Slug;
use  common\models\Posts;
/**
 * Site controller
 */
class FrontEndController extends Controller {
    public function beforeAction($action)
    {
        Yii::$app->view->title = 'Bất động sản hải dương';
        $this->getSeo();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function getSeo(){
        $slug = Slug::findOne(['value'=>Yii::$app->controller->action->uniqueId]);
        if ($slug){
            $post = Posts::findOne($slug->table_id);
            if ($post){
                $post->getSeoPost(true);
            }
        }
    }
}
