<?php

namespace frontend\modules\home\models;

use Yii;

class MemberFogotPassword extends \common\models\Member
{
    public $label_success;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [[ 'email'], 'required'],
            [[ 'email'], 'email'],
            ['email', 'checkEmail'],
        ];
    }
    public function checkEmail($attribute, $params) {
        $model = self::find()->where(['email'=>$this->email])->andWhere(['!=','status',self::STATUS_CREATE_BDS])->one();
        if (!$model) {
            $this->addError('email', "Khôno tìm thấy địa chỉ email");
        }
    }
    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'email' => Yii::t('app', 'Email'),
        ];
    }
}
